import pygame

GAME_NAME = 'GraviSwitch'

BLOCK_SIZE = 32

SCREEN_WIDTH = BLOCK_SIZE * 32
SCREEN_HEIGHT = BLOCK_SIZE * 18

SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

MAX_FPS = 60
SLOW_MODE = False
MUSIC = False
